### PR TITLE
fix: allow unmarshalling of 64 bit numbers as strings

### LINKED ISSUE #39: Error when parsing google.cloud.storage.object.v1.finalized events using storage.UnmarshalStorageObjectData
## Expected Behavior

We're able to parse the event and populate data into StorageObjectData object.

## Actual Behavior

Got the following error instead: 

```
{"level":"error","ts":1610564646.3508415,"logger":"fallback","caller":"client/invoker.go:66","msg":"call to Invoker.Invoke(...) has panicked: json: cannot unmarshal string into Go struct field StorageObjectData.generation of type int64","stacktrace":"..."}
```

pretty printed stacktrace: 
```go
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func2.1
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:66
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:969
main.Receive
        /app/main.go:35
reflect.Value.call
        /usr/local/go/src/reflect/value.go:476
reflect.Value.Call
        /usr/local/go/src/reflect/value.go:337
github.com/cloudevents/sdk-go/v2/client.(*receiverFn).invoke
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/receiver.go:86
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func2
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:69
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/invoker.go:71
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver.func2.1
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.3.1/client/client.go:233
```

### Event (in go object format)

```Validation: valid
Context Attributes,
  specversion: 1.0
  type: google.cloud.storage.object.v1.finalized
  source: //storage.googleapis.com/projects/_/buckets/events-quickstart-danglu-knative-dev-290519
  subject: objects/go-test-123.txt
  id: 1911674720947509
  time: 2021-01-13T19:03:20.8Z
  dataschema: https://raw.githubusercontent.com/googleapis/google-cloudevents/master/proto/google/events/cloud/storage/v1/data.proto
  datacontenttype: application/json
Extensions,
  knativearrivaltime: 2021-01-13T19:03:21.568106765Z
  knsourcetrigger: link0.8966907269185795
  traceparent: 00-31c5577593932217af33e2c0ab5dcf12-32037e59dd69f8b4-00
Data,
  {
    "kind": "storage#object",
    "id": "events-quickstart-danglu-knative-dev-290519/go-test-123.txt/1610564600595212",
    "selfLink": "https://www.googleapis.com/storage/v1/b/events-quickstart-danglu-knative-dev-290519/o/go-test-123.txt",
    "name": "go-test-123.txt",
    "bucket": "events-quickstart-danglu-knative-dev-290519",
    "generation": "1610564600595212",
    "metageneration": "1",
    "contentType": "application/octet-stream",
    "timeCreated": "2021-01-13T19:03:20.603Z",
    "updated": "2021-01-13T19:03:20.603Z",
    "storageClass": "STANDARD",
    "timeStorageClassUpdated": "2021-01-13T19:03:20.603Z",
    "size": "1682",
    "md5Hash": "DqB0N1pmMRX4mjv1llfoWQ==",
    "mediaLink": "https://www.googleapis.com/download/storage/v1/b/events-quickstart-danglu-knative-dev-290519/o/go-test-123.txt?generation=1610564600595212&alt=media",
    "contentLanguage": "en",
    "crc32c": "mA33eA==",
    "etag": "CIyGoNfMme4CEAE="
  }
```

### Code

go.mod

```
module xxxxx

go 1.13

require (
	github.com/cloudevents/sdk-go/v2 v2.3.1
	github.com/googleapis/google-cloudevents-go v0.0.0-20210109004349-be1f906e2061 // indirect
)
```

main.go

```go
import (
	"context"
	"fmt"
	"log"

	cloudevents "github.com/cloudevents/sdk-go/v2"
	"github.com/googleapis/google-cloudevents-go/cloud/storage/v1"
)

func Receive(event cloudevents.Event) {
        fmt.Printf("%+v\n", event)
	e, err := storage.UnmarshalStorageObjectData(event.Data())
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", e)
	fmt.Printf("Detected change in GCS bucket: %s\n", event.Subject())
}

func main() {
	c, err := cloudevents.NewDefaultClient()
	if err != nil {
		log.Fatalf("failed to create client, %v", err)
	}
	log.Fatal(c.StartReceiver(context.Background(), Receive))
}

```

### PR DESCRIPTION
**Pull request by grant**
Fixes https://github.com/googleapis/google-cloudevents-go/issues/39

See detailed conversation and latest comment here: https://github.com/googleapis/google-cloudevents-go/issues/39#issuecomment-782473649

- Runs the generator.
  - New postgen step: Allows for `string` option in 64 bit types.
- Runs `gofmt` since we just modified golang files (we didn't do this before, so the diff is larger than normal)
  - Another artifact is the the copyright year is updated.

Notice in the Golang code how `*64` types allow the JSON values for 64 bit numbers to be strings (they will always be JSON strings).

Main code to review is in `tools/src/postgen-64types.ts`.

---

Here's a general test you can perform to understand the difference between adding the `string` annotation:

```go
package main

import (
	"encoding/json"
	"fmt"
)

func main() {
	fmt.Println("Test:")

	var d MyType
	s := `{ "port": "1234123341234", "revenue": "34.45"}`
	err := json.Unmarshal([]byte(s), &d)

	if err == nil {
		fmt.Print(*d.Port)
	}
}

// MyType: test
type MyType struct {
	Port *int64 `json:"port,string,omitempty"`
	// Port *int64 `json:"port,omitempty"`
}
```

`go run .`

### CODE REVIEW

File: tools/gen.sh [hunk 1]
```diff
@@ -15,8 +15,10 @@ qt \
...
-
 # Run postgen
-cd tools
-npm start
+echo '- Running postgen step'
+(cd tools && npm start)
+
+# Re-format the golang files
+echo "- Re-format golang files"
+gofmt -s -w .
```
Comment (grayside) [inline tools/gen.sh:24]: No Action: Nice addition to the repo!

Good to see this is part of the pipeline now. It would have been better to see this in a separate PR but overall the fmt changes are limited because the existing code quality was not far off the standard.

File: tools/src/postgen-64types.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+ * To parse these values into an idiomatic value, i.e. an "int64" rather than "string", we modify
+ * the Golang fields for 64 bit types (int64, uint64, float64):
+ *
+ * Before:
+ *     Generation              *int64              `json:"generation,omitempty"`
+ * After:
+ *     Generation              *int64              `json:"generation,string,omitempty"`
+ *
+ * This modification currently cannot be done at the JSON schema + Quicktype level,
+ * as JSON schema does not have a representation for 64 bit numbers serialized as strings.
```
Comment (grayside) [inline tools/src/postgen-64types.ts:26]: nit: It's great to see the context provided by this comment. However, since it implies that if JSON-Schema did gain such support we'd want to change this implementation something to mark how to track the need for that change would help.

* Good: Add https://github.com/json-schema-org/json-schema-spec/issues/361 to the comment block.
* Better: File an issue in this repo providing context on the decision made so far, the issue to watch for changes, and add a TODO on the local issue to the comment block.

**Review by grayside — APPROVED** [review]
Great work solving this. I hadn't realized you could tag a string and have the decoder automatically handling the numeric conversion! Thanks for teaching me something new.

It would be great to add a deeper TODO on updating how we're handling int64 if JSON-schema spec is evolved. I've added a deeper note on this, but nothing I expect is surprising.

File: tools/src/postgen-64types.ts (hunk 2 above)
Comment (grant) [reply tools/src/postgen-64types.ts:26]: - Added GitHub issue.
- I am not going to file a local issue in this case, as it requires a specification change that isn't actionable in this repo. We can discuss more about this offine. Maybe we can file an issue in the google-cloudevents repo.
